language: python
python: 3.7

addons:
  chrome: stable

install:
  - pip install -r requirements.txt

script:
  - LANGUAGE=ru_RU.UTF-8
#  - pytest
  - py.test --testrail --tr-config=testrail.cfg
  - py.test  --tr-close-on-complete
