language: python
python: 3.7

addons:
  chrome: stable

install:
  - pip install -r requirements.txt

before_script:
  - python before.py

script:
#  - LANGUAGE=ru_RU.UTF-8
  - py.test --testrail --tr-config=testrail.cfg --tr-close-on-complete

after_success:
  - python after.py
